title: Open Source Android TV
logo: /assets/img/logo-tv-no-bg.png
description: A little guide that groups a few Devices and Softwares to help you building your Android Smart TV
show_downloads: true
theme: jekyll-theme-minimal
