title: Open Source Android TV
logo: /assets/img/logo-tv-no-bg.png
description: A little guide that brings to you a few Devices and Softwares for help you building your Android Smart TV
show_downloads: true
theme: jekyll-theme-minimal
